version: "3.9"

x-uffizzi:
  ingress:
    service: app
    port: 3000
  continuous_previews:
    delete_preview_after: 1h

services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
