version: '3'

services:
  app:
    image: greenfrontend/test-env:v1
    entrypoint: /bin/bash
    command:
      - "-c"
      - "REDIRECT_URL=$$UFFIZZI_URL/home ENDPOINT=$$UFFIZZI_URL/entrypoint node /app/app/app.js"

x-uffizzi:
  ingress:
    service: app
    port: 8080
    additional_subdomains:
      - "example-1"
      - "example-2"
      - "example-3"
      - "example-4"


  continuous_preview:
    delete_preview_after: 10h
